[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["mp3"] }
bevy_rapier3d = { version = "0.27", features = ["debug-render-3d"] }
bevy-inspector-egui = "0.27"
bevy_spritesheet_animation = "0.4"
leafwing-input-manager = { git = "https://github.com/Leafwing-Studios/leafwing-input-manager.git" }
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tracing = "0.1"
blenvy = "0.1.0-alpha.1"

[features]
default = []
dev = [ "bevy/file_watcher" ]
