[package]
name = "game"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

[dependencies]
bevy = { version = "0.18.1", features = ["mp3"] }
bevy_rapier3d = { version = "0.33" }
bevy_egui = "0.39"
bevy-inspector-egui = "0.36"
bevy_spritesheet_animation = "6.1"
leafwing-input-manager = "0.20"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tracing = "0.1"
bevy_skein = "0.5"

[features]
default = []
dev = [ "bevy/file_watcher", "bevy_rapier3d/debug-render-3d" ]
